spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DB_DATABASE?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: DB_USER
    password: DB_PASS
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none